# Generated by Django 5.0.6 on 2024-07-25 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todoitem',
            options={'verbose_name': 'ToDo Item'},
        ),
    ]
