# Generated by Django 5.0.6 on 2024-08-06 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0003_alter_todoitem_options_todoitem_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='title',
            field=models.CharField(max_length=25),
        ),
    ]
