# Generated by Django 5.1 on 2024-08-16 21:45

import todo_list.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0006_alter_todoitem_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='user',
            field=models.ForeignKey(default=todo_list.models.get_sentinel_user_id, on_delete=models.SET(todo_list.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
    ]
