# Generated by Django 5.1 on 2024-09-18 19:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0008_alter_todoitem_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
