# Generated by Django 5.1 on 2024-09-22 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0009_todoitem_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
