# Generated by Django 5.1 on 2024-08-16 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_alter_newuser_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newuser',
            options={'ordering': ('username',)},
        ),
    ]
