# Generated by Django 5.1 on 2024-08-16 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_alter_newuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newuser',
            options={'ordering': ('username',), 'verbose_name': 'Users'},
        ),
    ]
