# Generated by Django 5.1 on 2024-08-20 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_alter_newuser_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
    ]
