# Generated by Django 5.1 on 2024-08-20 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_alter_newuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='status',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
