# Generated by Django 5.1 on 2024-08-20 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_newuser_status_alter_newuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='avatar',
            field=models.ImageField(blank=True, default='static/img/default.jpg', upload_to='uploads/static/img'),
        ),
    ]
