# Generated by Django 5.1 on 2024-08-20 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_newuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='avatar',
            field=models.ImageField(blank=True, default='static/img/default.jpg', upload_to='uploads/static/avs'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='status',
            field=models.CharField(blank=True, default='Хмм, может поставишь себе новый статус?', max_length=250),
        ),
    ]
