# Generated by Django 5.1 on 2024-09-11 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_alter_newuser_avatar_alter_newuser_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='avatar',
            field=models.ImageField(blank=True, default='static/img/default.jpg', upload_to='avatars'),
        ),
    ]
