# Generated by Django 5.1 on 2024-09-18 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_alter_newuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='avatar',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='avatars'),
        ),
    ]
